project:
  type: website
  resources:
    - fonts
  preview:
    port: 4321

execute:
  freeze: auto
  
website:
  title: "Advent of Code"
  description: My solutions to Advent of Code
  repo-url: https://github.com/statsrhian/advent-of-code
  navbar:
    left:
      - 2024.qmd
    right:
      - icon: github
        href: https://github.com/statsrhian/
  open-graph: true

format:
  html:
    theme: 
      light: [cosmo, custom-light.scss]
      dark: custom-dark.scss
    css: styles.css
    code-block-border-left: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source



